### ISSUE TITLE
Thanks.

### ISSUE THREAD

**Issue by DaveDavenport** [bardisty/gruvbox-rofi#1]
These are very nice, I added it as submodule to rofi-themes.

Thanks,

Qball

**Comment by bardisty** [comment]
Awesome, thanks Dave!

**Comment by DaveDavenport** [comment]
In the next release rofi will include some themes and ship with the rofi-theme-selector script.
Is it ok to include these?

**Comment by bardisty** [comment]
Absolutely, please do.
